version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command:  apt-get update &&  apt-get install g++
      - run:
          name: Print the Current Time
          command: date
 
