version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: cmake
                   make 
                   ./a.out
      - run:
          name: Print the Current Time
          command: date
 
