version: 2
jobs:
   build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command:
                  if [ -f CMakeLists.txt ]
                  then
                      apt-get update && apt-get install -y --no-install-recommends &&  apt-get install -y g++ && g++ main.cpp 
                      ./a.out       
                 else
               
               echo "no cpp files found"
              fi  
                   
                   
      - run:
          name: Print the Current Time
          command: date 
 
