version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command:  apt-get update && apt-get install -y --no-install-recommends &&  apt-get install -y g++
      - run:
          name: Print the Current Time
          command: date
 
